### ISSUE TITLE
2016年度版5374データ集約

### ISSUE THREAD

**Issue by kwaka1208** [code4ikoma/5374#2]
コメント欄にそれぞれの作業ファイルを添付してください。

**Comment by acliss19xx** [comment]
9と１０です
[Uploading area_days09-10.zip…]()

**Comment by kwaka1208** [comment]
エリア3と4のデータを添付します
[area_days_3and4.csv.zip](https://github.com/code4ikoma/5374/files/181125/area_days_3and4.csv.zip)

**Comment by Akky45Remain** [comment]
エリア7と8
[area_days0708.zip](https://github.com/code4ikoma/5374/files/181127/area_days0708.zip)
のデータを添付します

**Comment by TsukaGit** [comment]
エリア　５，６

北大和,生駒管理センター,火 金,水,月1 月3,20160606 20160905 20161205 20170306 20991231
真弓,生駒管理センター,火 金,水,月1 月3,20160606 20160905 20161205 20170306 20991231
真弓南,生駒管理センター,火 金,水,月1 月3,20160606 20160905 20161205 20170306 20991231

あすか野,生駒管理センター,火 金,水,木1 木3,20160602 201560901 20161201 2017030 20991231
あすか台,生駒管理センター,火 金,水,木1 木3,20160602 201560901 20161201 2017030 20991231
上町,生駒管理センター,火 金,水,木1 木3,20160602 201560901 20161201 2017030 20991231
上町台,生駒管理センター,火 金,水,木1 木3,20160602 201560901 20161201 2017030 20991231
白庭台,生駒管理センター,火 金,水,木1 木3,20160602 201560901 20161201 2017030 20991231

**Comment by Akky45Remain** [comment]
エリア7と8のデータを添付します
[area_days07-08.zip](https://github.com/code4ikoma/5374/files/181130/area_days07-08.zip)

**Comment by tikoma** [comment]
1と2です。
[area_days.csv.zip](https://github.com/code4ikoma/5374/files/181131/area_days.csv.zip)

**Comment by kwaka1208** [comment]
エリア3と4のデータです。（修正版）
[area_days_3and4.csv.zip](https://github.com/code4ikoma/5374/files/181134/area_days_3and4.csv.zip)

**Comment by acliss19xx** [comment]
エリア ９　１０再送です。
[area_day09-10.zip](https://github.com/code4ikoma/5374/files/181136/area_day09-10.zip)

**Comment by Akky45Remain** [comment]
7と8のデータです
[area_days07-08.zip](https://github.com/code4ikoma/5374/files/181138/area_days07-08.zip)

**Comment by TsukaGit** [comment]
５、６　更新です。
[TSUKA_area_days.zip](https://github.com/code4ikoma/5374/files/181139/TSUKA_area_days.zip)

**Comment by takuya310** [comment]
皆さまご協力ありがとうございました！
